spring.application.name=finace

# ========================================
# Upload de arquivos
# ========================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=1MB
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB

# ========================================
# JWT
# ========================================
jwt.secret=MinhaChaveSecretaSuperSeguraCom32CaracteresOuMais1234567890
jwt.expiration=86400
logging.level.org.springframework.security=DEBUG

# ========================================
# PostgreSQL
# ========================================
spring.datasource.url=jdbc:postgresql://ep-cold-wave-axbaawdl.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VyF0q8HthpPT
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================================
# JPA / Hibernate
# ========================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ========================================
# Flyway
# ========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ========================================
# ✅ SWAGGER — CORRIGIDO DEFINITIVAMENTE!
# ========================================
springdoc.swagger-ui.path=/doc
springdoc.api-docs.path=/api-docs

# # ✅ APONTA para a SUA API
# springdoc.swagger-ui.url=

# # ✅ DESATIVA configuração remota (RESOLVE O ERRO!)
# springdoc.swagger-ui.config-url=

# ✅ Desativa validação e exemplos
springdoc.swagger-ui.validatorUrl=none
springdoc.swagger-ui.display-default-models=false
springdoc.swagger-ui.show-common-extensions=false

springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json

# ✅ CORRIGE a URL do Servidor no Swagger (RESOLVE O ERRO!)
springdoc.swagger-ui.server-url=https://cuddly-couscous-q7rv4vpx4jpj296r-8089.app.github.dev
springdoc.api-docs.server=https://cuddly-couscous-q7rv4vpx4jpj296r-8089.app.github.dev

server.port=8089