spring.application.name=finace


# ========================================
# Upload de arquivos
# ========================================
# file.upload-dir=/root/dev/finace/uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=1MB
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB

# ========================================
# JWT
# ========================================

jwt.secret=9a8b7c6d5e4f3a2b1c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b
jwt.expiration=86400
logging.level.org.springframework.security=DEBUG
# ========================================
# PostgreSQL
# ========================================
# ✅ URL SEM usuário e senha
spring.datasource.url=jdbc:postgresql://ep-cold-wave-axbaawdl.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require

# ✅ Usuário e senha SEPARADOS
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VyF0q8HthpPT
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=550000


# ========================================
# JPA / Hibernate
# ========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# ========================================
# Flyway
# ========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


server.port=8089

# postgresql://neondb_owner:npg_VyF0q8HthpPT@ep-cold-wave-axbaawdl.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require