### ============================================

### FINACE API

### Testes de Autenticação

### ============================================

@baseUrl = http://localhost:8089

### ============================================

### REGISTER - Criar usuário

### ============================================

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
"nome": "Jose Maria",
"email": "jmario@mail.com",
"senha": "12345678",
"cpf": "12345678908",
"telefone": "75999999999"
}

### ============================================

### LOGIN - Autenticar usuário

### ============================================

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
"email": "osmar1@mail.com",
"senha": "12345678"
}


